{{- if .Values.configMaps.file.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-python.configMapName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{ .Values.configMaps.file.fileName }}: |-
{{ .Files.Get "files/config.json" | indent 4 }}
---
{{- end }}
{{- if .Values.configMaps.env.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-python.envConfigMapName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMaps.env.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
