{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "devops-python.headlessServiceName" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.statefulset.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.statefulset.updateStrategy.type }}
    {{- if eq .Values.statefulset.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      partition: {{ .Values.statefulset.updateStrategy.rollingUpdate.partition }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "devops-python.podAnnotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "devops-python.serviceAccountName" . }}
      automountServiceAccountToken: {{ ternary true .Values.serviceAccount.automount .Values.vault.enabled }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- include "devops-python.initContainers" . | nindent 6 }}
      containers:
        - name: {{ include "common.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- include "devops-python.volumeMounts" . | nindent 10 }}
          env:
            {{- include "devops-python.envVars" . | nindent 12 }}
          {{- if or .Values.configMaps.env.enabled .Values.secrets.enabled }}
          envFrom:
            {{- if .Values.configMaps.env.enabled }}
            - configMapRef:
                name: {{ include "devops-python.envConfigMapName" . }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ include "devops-python.secretName" . }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            {{- toYaml (omit .Values.probes.startup "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.probes.liveness "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.probes.readiness "enabled") | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      {{- if or .Values.configMaps.file.enabled .Values.initContainers.enabled }}
      volumes:
        {{- if .Values.configMaps.file.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "devops-python.configMapName" . }}
        {{- end }}
        {{- if .Values.initContainers.enabled }}
        - name: init-shared
          emptyDir: {}
        {{- end }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data-volume
        labels:
          {{- include "common.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
{{- end }}
