---
docker_repo_arch_map:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64

docker_prereq_packages:
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_users:
  - ubuntu

docker_service_state: started
docker_service_enabled: true
