---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ common_update_cache_valid_time | int }}"

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set system timezone
  ansible.builtin.command: "timedatectl set-timezone {{ common_timezone }}"
  when: ansible_facts.date_time.tz != common_timezone
  changed_when: true
