---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ common_update_cache_valid_time | int }}"

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set system timezone
  ansible.builtin.command: "timedatectl set-timezone {{ common_timezone }}"
  when: ansible_facts.date_time.tz != common_timezone
  changed_when: true

- name: Ensure operator user exists
  ansible.builtin.user:
    name: "{{ app_admin_user }}"
    shell: /bin/bash
    groups: "{{ app_admin_groups | join(',') }}"
    append: true
    create_home: true

- name: Ensure operator .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ app_admin_user }}/.ssh"
    state: directory
    owner: "{{ app_admin_user }}"
    group: "{{ app_admin_user }}"
    mode: "0700"
