---
- name: Deploy All Applications
  hosts: webservers
  become: true

  tasks:
    - name: Deploy Python application
      ansible.builtin.include_role:
        name: web_app
      vars:
        app_name: devops-python
        docker_image: vladkuznetsov/devops-info-service
        docker_tag: latest
        app_port: 8000
        app_internal_port: 8000
        compose_project_dir: /opt/devops-python
      tags:
        - web_app

    - name: Deploy bonus application
      ansible.builtin.include_role:
        name: web_app
      vars:
        app_name: devops-go
        docker_image: vladkuznetsov/devops-info-service-go
        docker_tag: latest
        app_port: 8001
        app_internal_port: 8080
        compose_project_dir: /opt/devops-go
      tags:
        - web_app
