---
- name: Full Lab 06 Provisioning and Deployment
  hosts: webservers
  become: true

  roles:
    - role: common
      tags:
        - common
    - role: docker
      tags:
        - docker
    - role: web_app
      tags:
        - web_app
