replicaCount: 3

image:
  tag: lab12

service:
  type: LoadBalancer
  nodePort: null

env:
  DEPLOYMENT_TRACK: prod

app:
  environment: prod
  logLevel: info

configMaps:
  env:
    data:
      APP_ENV: prod
      LOG_LEVEL: info

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 40
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 8
    periodSeconds: 3
