replicaCount: 3

image:
  tag: lab13

service:
  type: ClusterIP
  nodePort: null

env:
  DEPLOYMENT_TRACK: prod

app:
  environment: prod
  logLevel: info

configMaps:
  env:
    data:
      APP_NAME: devops-info-service
      APP_ENV: prod
      LOG_LEVEL: info
      FEATURE_VISITS_COUNTER: "true"
      VISITS_FILE: /data/visits

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 40
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 8
    periodSeconds: 3
