replicaCount: 1

image:
  tag: lab12

service:
  type: NodePort
  nodePort: 31080

env:
  DEPLOYMENT_TRACK: dev

app:
  environment: dev
  logLevel: debug

configMaps:
  env:
    data:
      APP_ENV: dev
      LOG_LEVEL: debug

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
