replicaCount: 2

image:
  tag: lab13

service:
  type: ClusterIP
  nodePort: null

env:
  DEPLOYMENT_TRACK: dev

app:
  environment: dev
  logLevel: debug

configMaps:
  env:
    data:
      APP_NAME: devops-info-service
      APP_ENV: dev
      LOG_LEVEL: debug
      FEATURE_VISITS_COUNTER: "true"
      VISITS_FILE: /data/visits

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
