nameOverride: ""
fullnameOverride: ""

replicaCount: 3

image:
  repository: devops-info-service-py
  tag: lab14
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  nodePort: null

env:
  DEPLOYMENT_TRACK: helm

app:
  environment: dev
  logLevel: info

configMaps:
  file:
    enabled: true
    name: ""
    mountPath: /config
    fileName: config.json
  env:
    enabled: true
    name: ""
    data:
      APP_NAME: devops-info-service
      APP_ENV: dev
      LOG_LEVEL: info
      FEATURE_VISITS_COUNTER: "true"
      VISITS_FILE: /data/visits

secrets:
  enabled: true
  type: Opaque
  name: ""
  data:
    username: "change-me-username"
    password: "change-me-password"

serviceAccount:
  create: true
  name: ""
  automount: false

vault:
  enabled: false
  role: devops-python-role
  secretPath: secret/data/myapp/config
  renderFile: config
  command: "chmod 0440 /vault/secrets/config"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  name: ""
  mountPath: /data
  accessModes:
    - ReadWriteOnce
  size: 100Mi
  storageClass: ""

probes:
  startup:
    enabled: true
    httpGet:
      path: /health
      port: http
    periodSeconds: 2
    failureThreshold: 30
  liveness:
    enabled: true
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    enabled: true
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

hooks:
  enabled: false
  cleanupPolicy: before-hook-creation,hook-succeeded
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  preInstall:
    enabled: true
    weight: "-5"
    sleepSeconds: 12
  postInstall:
    enabled: true
    weight: "5"
    sleepSeconds: 12

rollout:
  enabled: false
  strategy: canary
  canary:
    maxSurge: 1
    maxUnavailable: 0
  blueGreen:
    autoPromotionEnabled: false
  analysis:
    enabled: false
    path: /health
    jsonPath: "{$.status}"
    successCondition: result == 'healthy'
    interval: 10s
    count: 3
    failureLimit: 1

statefulset:
  enabled: false
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

initContainers:
  enabled: false
  sharedVolume:
    mountPath: /init-data
  download:
    enabled: false
    url: https://example.com
    outputPath: /init-data/index.html
    image:
      repository: busybox
      tag: "1.36"
      pullPolicy: IfNotPresent
  waitForService:
    enabled: false
    host: kubernetes.default.svc.cluster.local
    intervalSeconds: 2
    image:
      repository: busybox
      tag: "1.36"
      pullPolicy: IfNotPresent

serviceMonitor:
  enabled: false
  labels:
    release: monitoring
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics
