nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: devops-info-service-go
  tag: lab10
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 31081

env: {}

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

probes:
  startup:
    enabled: true
    httpGet:
      path: /health
      port: http
    periodSeconds: 2
    failureThreshold: 30
  liveness:
    enabled: true
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    enabled: true
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
